version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  hof-csl-app:
    env_file: devcontainer.env
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: Dockerfile
    
    networks:
      - csl-shared-network
    ports:
      - "8080:8080"
    hostname: hof-app
    depends_on:
      - redis
      #- file-vault

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app:cached

    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
    command: sleep infinity

  redis:
    image: "redis:alpine"
    networks:
      - csl-shared-network
    hostname: hof-redis
    ports:
      - "6379:6379"

  file-vault:
    env_file: devcontainer.env
    image: quay.io/ukhomeofficedigital/file-vault:f4cd1ece1caddc3bfbc8f5db761c593fda79ef12
    networks:
      - csl-shared-network
    hostname: hof-file-vault
    environment:
      - DEBUG=*
    ports:
      - "3000:3000"

  hof-rds-api:
    env_file: devcontainer.env
    image: quay.io/ukhomeofficedigital/hof-rds-api:16bc712744851373e533d94ecf04724836be8247
    networks:
      - csl-shared-network
    hostname: hof-rds-api
    environment:
      - SERVICE_NAME=csl
      - NODE_ENV=local
    ports:
      - "5000:5000"

networks:
  csl-shared-network:
    driver: bridge
